server:
  port: 8084
spring:
  redis:
    password: ok
    host: 192.168.1.40
  activemq:
    broker-url: tcp://192.168.1.40:61616
dubbo:
  consumer:
    check: false
  application:
    name: qg-goods-consumer
  registry:
    address: zookeeper://192.168.1.40:2181
  protocol:
    name: dubbo